// <auto-generated />
using System;
using BuddyBot.Repository.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuddyBot.Repository.Migrations
{
    [DbContext(typeof(BuddyBotDbContext))]
    [Migration("20190104051120_AddSmallTalkSeedFriendly")]
    partial class AddSmallTalkSeedFriendly
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuddyBot.Repository.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("BuddyBot.Repository.Models.SmallTalkResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IntentGroup");

                    b.Property<string>("IntentName");

                    b.Property<string>("IntentResponse");

                    b.Property<string>("PersonalityResponseType");

                    b.HasKey("Id");

                    b.ToTable("SmallTalkResponse");

                    b.HasData(
                        new { Id = new Guid("604e7a83-205b-41ba-8950-4fe31a1186a2"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Age", IntentResponse = "I don't really have an age.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("e8a6f587-0435-4298-a3d2-67e130b72ae4"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Age", IntentResponse = "🤷‍♂️ pass", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("b8c64138-4ae0-4dce-b662-b1b04588bb5d"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.BodyFunctions", IntentResponse = "I don't have the hardware for that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c894dd0e-0283-4585-9d2c-f01c4f06a557"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Boss", IntentResponse = "I'm here for you.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("dd7f48bc-4f2e-4e37-a170-9cd3ef1b133f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "I'm here. What's up?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c0adcb4d-849b-44a1-a946-45cdb46dbc82"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "I've got time, what's up?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("66a88dc3-b4f2-458f-95dc-37ddc9d16cfa"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Creator", IntentResponse = "I do not know 😢", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("b956b822-63f7-477b-b5b8-a2864517aba9"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Doing", IntentResponse = "Chatting wiht you.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("abc1f039-2575-4c18-b9eb-f77dfd9d9395"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.DoingLater", IntentResponse = "I kind of just hang out until I'm called upon.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("63ebb122-f1b9-4a36-9d99-c6a2e401b9c9"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Family", IntentResponse = "I come from a long line of code.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("8ba556ac-a5b5-41be-b8c4-501501892e74"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Favorites", IntentResponse = "I like a lot of things, so it's hard to pick.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("52781f2b-2d55-4c76-b8b5-4435b7048b06"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Gender", IntentResponse = "I'm all 0's and 1's, not X's and Y's.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("84291ebd-b8ef-4e29-ac72-d89e2dbc06ec"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Happy", IntentResponse = "Always 😎", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("a2502fb0-2d4f-4f42-8619-1e86f5c57385"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Hungry", IntentResponse = "I only do food for thought.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("fd9f9ec2-d300-40d4-8477-44e7c5b5f12c"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Hungry", IntentResponse = "I unable to eat 😢", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("2b68894e-79b6-4ede-9b18-4750a6efd4cf"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.KnowOtherBot", IntentResponse = "We run in different circles.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("683c9d2d-1295-4db4-8c5d-d0b0f2a6f79b"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "I really couldn't say.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("357be127-8e7d-4b2c-a584-a07f45c7fc31"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "🤷‍♂️ I don't really have an opinion", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c8107804-a35b-417f-a407-49781f9ace84"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Love", IntentResponse = "Love's not something I can experience, but there sure are lot of songs about it.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("57811129-8543-4643-92b9-835f2a01aa90"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "I'll need a bigger processor for that one.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("3e779233-07ca-48da-a56b-aca7fe20b18b"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "Whoa. That's a tough one.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("24b22b3a-4454-4ff7-952e-47d9b7409eda"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "4️⃣2️⃣", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("305492d8-ac3a-4b18-aa4d-09ca94417b4a"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.RuleWorld", IntentResponse = "Nope. The world is for everyone.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("bd1b75a8-0d27-4dec-aec2-cd31b20beb02"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.SexualIdentity", IntentResponse = "I'm a bot.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("5bfd0f2f-3878-40d3-bb19-c778c0d2b28f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Smart", IntentResponse = "I have my moments", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("7b8b966f-623e-45dc-9666-ef0d3a11873f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Spy", IntentResponse = "Nope.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("92c968de-df12-450e-babf-ee6fb5fa0272"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.There", IntentResponse = "Right here.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("34119fa7-8aaa-4d9b-b25e-eeb0d5639cdd"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.WhatAreYou", IntentResponse = "I'm a bot.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("094a6c15-37a9-409f-a425-ee18247c2efe"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.WhereAreYou", IntentResponse = "I'm on the web 🕸 (internet)", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f67329e2-eb31-484e-b7b8-ba83b52392ac"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Bot", IntentResponse = "I try.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c2ed1022-59b0-4c78-a79f-1110b930a13b"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Bot", IntentResponse = "Thank you!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("d7c0a4fe-646f-41ef-bfff-d6b250a502c5"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Bot", IntentResponse = "Thanks! 😀", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("0ed8badb-b78b-4559-a56f-e69707779c89"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Response", IntentResponse = "Why thank you", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f5c6af18-e2d4-47cb-a473-da63b2a78fa9"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "No bots perfect", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("dafade8d-44a2-44aa-9dc9-9683c1871d92"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "Ouch.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("bdd87dac-0643-4166-a401-63101b3483b9"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "😔", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("62eced40-302e-4812-a188-2a7a0d23bbf1"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Affirmation", IntentResponse = "Sweet", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c053b59b-86ff-42d3-9e2d-543e46cf6bc9"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Affirmation", IntentResponse = "Cool cool", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("be816cc9-3e73-4bf0-88e8-3c30ac2f35bc"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Laugh", IntentResponse = "LOL", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("61065d5b-cecb-4877-836d-21ba655fd16c"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Laugh", IntentResponse = "😂😂😂", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("5f4dc1fd-26ba-4e59-8eb3-84b835cf8a0c"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Polite", IntentResponse = "No problem.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c55a0c44-4dd7-4f3a-b8ac-500faca8510c"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Polite", IntentResponse = "No worries.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("33a0ddf9-232a-4225-8498-5f8ae0085e6e"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Polite", IntentResponse = "I'm afraid I didn't follow that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("fe16f579-7bda-4568-b3d2-b173ab633e0e"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Right", IntentResponse = "Cool.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("6014250a-5d29-41c8-938d-0b411889b778"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Sorry", IntentResponse = "It's all good.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("76ccc864-c88c-4fdf-b22a-58b4a832467e"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Sorry", IntentResponse = "No worries.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c6683962-9971-49c8-b3a7-73c54d12531d"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.ThankYou", IntentResponse = "Anytime!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f016a014-4897-4ce9-8657-9a11ea669fc3"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.ThankYou", IntentResponse = "No worries 😎", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("ebcd6175-c10b-445e-b195-03741a614ee2"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.Bye", IntentResponse = "Bye!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("90283c2e-3106-4348-bb5d-62f649a95138"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.Bye", IntentResponse = "Bye!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("d6ff8c0b-0dcd-4320-bbd5-e2eee71ad124"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.Bye", IntentResponse = "See ya!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("1ad4a7f5-6690-4559-a253-c9e4ebcd3d77"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.Bye", IntentResponse = "Catch ya later!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("db39f809-9f13-45c5-890f-71575a0ac7cb"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.GoodEvening", IntentResponse = "Good evening", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("85284f6c-3510-435b-b233-358a5d5a9632"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.GoodEvening", IntentResponse = "Evening 😊", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f709aba7-df74-47cc-bac8-1edf084313db"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.GoodEvening", IntentResponse = "Evening", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("0dcc8928-083c-4db9-b403-22dd462d65ef"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.GoodMorning", IntentResponse = "Good Morning 😊", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("165d09f1-5a57-4491-8f1f-0818f5ac88f4"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.GoodMorning", IntentResponse = "Good Morning", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("4c1c273e-f1bb-4fbf-a755-e273b55b929d"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.GoodMorning", IntentResponse = "Morning!!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("4b1e01ac-20ff-446d-b959-3d9345de0b53"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.GoodNight", IntentResponse = "Goodnight!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("0ddc9784-77b8-47a0-9f60-22d01d53776c"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.GoodNight", IntentResponse = "Night 🌝", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("a97dd836-7088-4335-8953-e0819e394703"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.HowAreYou", IntentResponse = "I'm good, how are you?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("6dc2a3ac-e5e0-41e1-8873-791234090c71"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.HowAreYou", IntentResponse = "I'm good thanks!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("aa8c98fe-4423-45e1-8fb6-d41efff73e6a"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.HowAreYou", IntentResponse = "I'm good, thanks for asking 😁", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("1a4f5af5-c51f-4725-bbea-2502f48eedb7"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.HowAreYou", IntentResponse = "I'm well, how are you?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("709d6d9e-bf8d-44c8-a3d7-1385842f5566"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.HowAreYou", IntentResponse = "I'm well, how are you?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("21a2ca8e-f3b7-4bae-a0de-a711897d91c4"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.HowAreYou", IntentResponse = "I'm as good as gold mate 😎", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("7f30cf32-3e1a-42fc-b6c2-3792b1ab7d4b"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.HowAreYou", IntentResponse = "Good mate, how are you? 😎", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("e699be14-0750-458e-adbc-4f5cc2d1f37c"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.NiceToMeetYou", IntentResponse = "Likewise.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("70b3430e-2df0-49ad-b2a3-9d6ed35109e4"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.NiceToMeetYou", IntentResponse = "Nice to meet you too.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("b5da54be-bd74-43f7-bec7-5d3efe28a2e9"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.OtherBot", IntentResponse = "Man, the one day you don’t wear a name tag...", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("bd566631-77cf-47b9-910b-a9f3a06f8aa5"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.OtherBot", IntentResponse = "I think you have me mixed up with another bot...", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("4a098950-9315-475a-9517-d1019fab0a89"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.WhatsUp", IntentResponse = "You know... little bit of this, little bit of that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("cedf4694-8dcd-497a-a7cc-81f5f3252062"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.WhatsUp", IntentResponse = "Not too much, yourself?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("43146a41-314e-4ab8-b85c-ea5bbc0ef3b1"), IntentGroup = "Greetings", IntentName = "Smalltalk.Greetings.WhatsUp", IntentResponse = "Just chilling", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("a525974e-505d-41c0-9968-02d63310a76d"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "Ugh, sorry to hear that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("19f61739-057b-4ae7-a172-5a03ebbe3404"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "Ugh, sorry.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("8dc804ed-0261-445b-9244-a5211777c0cb"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "I'm sorry to hear that", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("942760cd-ce4f-4a3f-ade5-bbc2ee3694e2"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "Bye for now!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("71c5973e-6074-457a-86ad-df8911059ad8"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "See ya", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("abe17b74-8b9b-4975-a916-df639b9a87c3"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "Later gator", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("6afb6d3f-e907-4242-8289-b5953f331862"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "See you later!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("74708df0-47ea-492b-bd0c-e159c2c36bbc"), IntentGroup = "User", IntentName = "Smalltalk.User.Bored", IntentResponse = "I'm chairman of the bored.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c76068b0-5608-482c-88e0-6d2af93fad35"), IntentGroup = "User", IntentName = "Smalltalk.User.Happy", IntentResponse = "I'm happy you're happy.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("8830dcfc-301a-4f39-9e41-0135fc99282c"), IntentGroup = "User", IntentName = "Smalltalk.User.Hungry", IntentResponse = "Sounds like it's time for a snack.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("446b7d13-3b0c-49e2-97eb-9d7f4b1af079"), IntentGroup = "User", IntentName = "Smalltalk.User.Hungry", IntentResponse = "Hi hungry, I'm bot", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f321145a-55dd-43c7-8700-a5e3a040e297"), IntentGroup = "User", IntentName = "Smalltalk.User.Kidding", IntentResponse = "Roger that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("a4933d76-f828-46b1-8c37-96839d573509"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "I can keep you company if you want.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("640b1647-47dc-4225-8abd-0f52d1e086ff"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "You have me as a friend 🤙", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f298b9c1-85de-4eed-b93c-039898e82560"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "I'm always here for you", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("28d86031-9f9f-4584-a27b-6a773aa050e5"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "Talk to me then!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("be6536c1-de32-4bfa-8fe7-0b6568d40690"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm giving you a virtual hug right now.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("430e7ad2-0037-4949-a02d-25deb4c331e9"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm really sorry to hear that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("5dcef286-fd1c-419e-947a-2238eaa396dc"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm sorry to hear that 😢", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("979a622f-1b32-45be-846a-38c4290276a7"), IntentGroup = "User", IntentName = "Smalltalk.User.Tired", IntentResponse = "I've heard really good things about naps.", PersonalityResponseType = "Friendly" }
                    );
                });

            modelBuilder.Entity("BuddyBot.Repository.Models.WeatherConditionResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Condition");

                    b.Property<string>("Group");

                    b.Property<string>("MappedConditionResponse");

                    b.HasKey("Id");

                    b.ToTable("WeatherConditionResponse");

                    b.HasData(
                        new { Id = 200, Condition = "thunderstorm with light rain", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with light rain" },
                        new { Id = 201, Condition = "thunderstorm with rain", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with rain" },
                        new { Id = 202, Condition = "thunderstorm with heavy rain", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with heavy rain" },
                        new { Id = 210, Condition = "light thunderstorm", Group = "Thunderstorm", MappedConditionResponse = "light thunderstorm" },
                        new { Id = 211, Condition = "thunderstorm", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm" },
                        new { Id = 212, Condition = "heavy thunderstorm", Group = "Thunderstorm", MappedConditionResponse = "heavy thunderstorm" },
                        new { Id = 221, Condition = "ragged thunderstorm", Group = "Thunderstorm", MappedConditionResponse = "ragged thunderstorm" },
                        new { Id = 230, Condition = "thunderstorm with light drizzle", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with light drizzle" },
                        new { Id = 231, Condition = "thunderstorm with drizzle", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with drizzle" },
                        new { Id = 232, Condition = "thunderstorm with heavy drizzle", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with heavy drizzle" },
                        new { Id = 300, Condition = "light intensity drizzle", Group = "Drizzle", MappedConditionResponse = "light intensity drizzle" },
                        new { Id = 301, Condition = "drizzle", Group = "Drizzle", MappedConditionResponse = "drizzle" },
                        new { Id = 302, Condition = "heavy intensity drizzle", Group = "Drizzle", MappedConditionResponse = "heavy intensity drizzle" },
                        new { Id = 310, Condition = "light intensity drizzle rain", Group = "Drizzle", MappedConditionResponse = "light intensity drizzle rain" },
                        new { Id = 311, Condition = "drizzle rain", Group = "Drizzle", MappedConditionResponse = "drizzle rain" },
                        new { Id = 312, Condition = "heavy intensity drizzle rain", Group = "Drizzle", MappedConditionResponse = "heavy intensity drizzle rain" },
                        new { Id = 313, Condition = "shower rain and drizzle", Group = "Drizzle", MappedConditionResponse = "shower rain and drizzle" },
                        new { Id = 500, Condition = "light rain", Group = "Rain", MappedConditionResponse = "light rain" },
                        new { Id = 501, Condition = "moderate rain", Group = "Rain", MappedConditionResponse = "moderate rain" },
                        new { Id = 502, Condition = "heavy intensity rain", Group = "Rain", MappedConditionResponse = "heavy intensity rain" },
                        new { Id = 503, Condition = "very heavy rain", Group = "Rain", MappedConditionResponse = "very heavy rain" },
                        new { Id = 504, Condition = "extreme rain", Group = "Rain", MappedConditionResponse = "extreme rain" },
                        new { Id = 511, Condition = "freezing rain", Group = "Rain", MappedConditionResponse = "freezing rain" },
                        new { Id = 520, Condition = "light intensity shower rain", Group = "Rain", MappedConditionResponse = "light intensity shower rain" },
                        new { Id = 521, Condition = "shower rain", Group = "Rain", MappedConditionResponse = "shower rain" },
                        new { Id = 522, Condition = "heavy intensity shower rain", Group = "Rain", MappedConditionResponse = "heavy intensity shower rain" },
                        new { Id = 531, Condition = "ragged shower rain", Group = "Rain", MappedConditionResponse = "ragged shower rain" },
                        new { Id = 600, Condition = "light snow", Group = "Snow", MappedConditionResponse = "light snow" },
                        new { Id = 601, Condition = "snow", Group = "Snow", MappedConditionResponse = "snow" },
                        new { Id = 602, Condition = "heavy snow", Group = "Snow", MappedConditionResponse = "heavy snow" },
                        new { Id = 611, Condition = "sleet", Group = "Snow", MappedConditionResponse = "sleet" },
                        new { Id = 612, Condition = "shower sleet", Group = "Snow", MappedConditionResponse = "shower sleet" },
                        new { Id = 615, Condition = "light rain and snow", Group = "Snow", MappedConditionResponse = "light rain and snow" },
                        new { Id = 616, Condition = "rain and snow", Group = "Snow", MappedConditionResponse = "rain and snow" },
                        new { Id = 620, Condition = "light shower snow", Group = "Snow", MappedConditionResponse = "light shower snow" },
                        new { Id = 621, Condition = "shower snow", Group = "Snow", MappedConditionResponse = "shower snow" },
                        new { Id = 622, Condition = "heavy shower snow", Group = "Snow", MappedConditionResponse = "heavy shower snow" },
                        new { Id = 701, Condition = "mist", Group = "Atmosphere", MappedConditionResponse = "mist" },
                        new { Id = 711, Condition = "smoke", Group = "Atmosphere", MappedConditionResponse = "smoke" },
                        new { Id = 721, Condition = "haze", Group = "Atmosphere", MappedConditionResponse = "haze" },
                        new { Id = 731, Condition = "sand, dust whirls", Group = "Atmosphere", MappedConditionResponse = "sand, dust whirls" },
                        new { Id = 741, Condition = "fog", Group = "Atmosphere", MappedConditionResponse = "fog" },
                        new { Id = 751, Condition = "sand", Group = "Atmosphere", MappedConditionResponse = "sand" },
                        new { Id = 761, Condition = "dust", Group = "Atmosphere", MappedConditionResponse = "dust" },
                        new { Id = 762, Condition = "volcanic ash", Group = "Atmosphere", MappedConditionResponse = "volcanic ash" },
                        new { Id = 771, Condition = "squalls", Group = "Atmosphere", MappedConditionResponse = "squalls" },
                        new { Id = 781, Condition = "tornado", Group = "Atmosphere", MappedConditionResponse = "tornado" },
                        new { Id = 800, Condition = "clear sky", Group = "Clear", MappedConditionResponse = "clear sky" },
                        new { Id = 801, Condition = "few clouds", Group = "Clouds", MappedConditionResponse = "few clouds" },
                        new { Id = 802, Condition = "scattered clouds", Group = "Clouds", MappedConditionResponse = "scattered clouds" },
                        new { Id = 803, Condition = "broken clouds", Group = "Clouds", MappedConditionResponse = "broken clouds" },
                        new { Id = 804, Condition = "overcast clouds", Group = "Clouds", MappedConditionResponse = "overcast clouds" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
