// <auto-generated />
using System;
using BuddyBot.Repository.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuddyBot.Repository.Migrations
{
    [DbContext(typeof(BuddyBotDbContext))]
    [Migration("20190115070622_AddSmallTalkResponseSeedData")]
    partial class AddSmallTalkResponseSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuddyBot.Repository.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("BuddyBot.Repository.Models.SmallTalkResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IntentGroup");

                    b.Property<string>("IntentName");

                    b.Property<string>("IntentResponse");

                    b.Property<string>("PersonalityResponseType");

                    b.HasKey("Id");

                    b.ToTable("SmallTalkResponse");
                });

            modelBuilder.Entity("BuddyBot.Repository.Models.WeatherConditionResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Condition");

                    b.Property<string>("Group");

                    b.Property<string>("MappedConditionResponse");

                    b.HasKey("Id");

                    b.ToTable("WeatherConditionResponse");
                });
#pragma warning restore 612, 618
        }
    }
}
