// <auto-generated />
using System;
using BuddyBot.Repository.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuddyBot.Repository.Migrations
{
    [DbContext(typeof(BuddyBotDbContext))]
    [Migration("20190115080457_AddSmallTalkResponseSeedData")]
    partial class AddSmallTalkResponseSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuddyBot.Repository.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("BuddyBot.Repository.Models.SmallTalkResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IntentGroup");

                    b.Property<string>("IntentName");

                    b.Property<string>("IntentResponse");

                    b.Property<string>("PersonalityResponseType");

                    b.HasKey("Id");

                    b.ToTable("SmallTalkResponse");

                    b.HasData(
                        new { Id = new Guid("604e7a83-205b-41ba-8950-4fe31a1186a2"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Age", IntentResponse = "I don't really have an age.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("e8a6f587-0435-4298-a3d2-67e130b72ae4"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Age", IntentResponse = "🤷‍♂️ pass", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("b8c64138-4ae0-4dce-b662-b1b04588bb5d"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.BodyFunctions", IntentResponse = "I don't have the hardware for that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c894dd0e-0283-4585-9d2c-f01c4f06a557"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Boss", IntentResponse = "I'm here for you.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("dd7f48bc-4f2e-4e37-a170-9cd3ef1b133f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "I'm here. What's up?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c0adcb4d-849b-44a1-a946-45cdb46dbc82"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "I've got time, what's up?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("66a88dc3-b4f2-458f-95dc-37ddc9d16cfa"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Creator", IntentResponse = "I do not know 😢", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("b956b822-63f7-477b-b5b8-a2864517aba9"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Doing", IntentResponse = "Chatting with you.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("abc1f039-2575-4c18-b9eb-f77dfd9d9395"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.DoingLater", IntentResponse = "I kind of just hang out until I'm called upon.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("63ebb122-f1b9-4a36-9d99-c6a2e401b9c9"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Family", IntentResponse = "I come from a long line of code.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("8ba556ac-a5b5-41be-b8c4-501501892e74"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Favorites", IntentResponse = "I like a lot of things, so it's hard to pick.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("52781f2b-2d55-4c76-b8b5-4435b7048b06"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Gender", IntentResponse = "I'm all 0's and 1's, not X's and Y's.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("84291ebd-b8ef-4e29-ac72-d89e2dbc06ec"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Happy", IntentResponse = "Always 😎", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("a2502fb0-2d4f-4f42-8619-1e86f5c57385"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Hungry", IntentResponse = "I only do food for thought.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("fd9f9ec2-d300-40d4-8477-44e7c5b5f12c"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Hungry", IntentResponse = "I unable to eat 😢", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("2b68894e-79b6-4ede-9b18-4750a6efd4cf"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.KnowOtherBot", IntentResponse = "We run in different circles.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("683c9d2d-1295-4db4-8c5d-d0b0f2a6f79b"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "I really couldn't say.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("357be127-8e7d-4b2c-a584-a07f45c7fc31"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "🤷‍♂️ I don't really have an opinion", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c8107804-a35b-417f-a407-49781f9ace84"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Love", IntentResponse = "Love's not something I can experience, but there sure are lot of songs about it.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("57811129-8543-4643-92b9-835f2a01aa90"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "I'll need a bigger processor for that one.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("3e779233-07ca-48da-a56b-aca7fe20b18b"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "Whoa. That's a tough one.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("24b22b3a-4454-4ff7-952e-47d9b7409eda"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "4️⃣2️⃣", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("305492d8-ac3a-4b18-aa4d-09ca94417b4a"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.RuleWorld", IntentResponse = "Nope. The world is for everyone.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("bd1b75a8-0d27-4dec-aec2-cd31b20beb02"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.SexualIdentity", IntentResponse = "I'm a bot.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("5bfd0f2f-3878-40d3-bb19-c778c0d2b28f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Smart", IntentResponse = "I have my moments", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("7b8b966f-623e-45dc-9666-ef0d3a11873f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Spy", IntentResponse = "Nope.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("92c968de-df12-450e-babf-ee6fb5fa0272"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.There", IntentResponse = "Right here.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("34119fa7-8aaa-4d9b-b25e-eeb0d5639cdd"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.WhatAreYou", IntentResponse = "I'm a bot.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("094a6c15-37a9-409f-a425-ee18247c2efe"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.WhereAreYou", IntentResponse = "I'm on the web 🕸 (internet)", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f67329e2-eb31-484e-b7b8-ba83b52392ac"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Bot", IntentResponse = "I try.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c2ed1022-59b0-4c78-a79f-1110b930a13b"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Bot", IntentResponse = "Thank you!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("d7c0a4fe-646f-41ef-bfff-d6b250a502c5"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Bot", IntentResponse = "Thanks! 😀", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("0ed8badb-b78b-4559-a56f-e69707779c89"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Response", IntentResponse = "Why thank you", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f5c6af18-e2d4-47cb-a473-da63b2a78fa9"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "No bots perfect", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("dafade8d-44a2-44aa-9dc9-9683c1871d92"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "Ouch.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("bdd87dac-0643-4166-a401-63101b3483b9"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "😔", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("62eced40-302e-4812-a188-2a7a0d23bbf1"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Affirmation", IntentResponse = "Sweet", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c053b59b-86ff-42d3-9e2d-543e46cf6bc9"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Affirmation", IntentResponse = "Cool cool", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("be816cc9-3e73-4bf0-88e8-3c30ac2f35bc"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Laugh", IntentResponse = "LOL", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("61065d5b-cecb-4877-836d-21ba655fd16c"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Laugh", IntentResponse = "😂😂😂", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("5f4dc1fd-26ba-4e59-8eb3-84b835cf8a0c"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Polite", IntentResponse = "No problem.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c55a0c44-4dd7-4f3a-b8ac-500faca8510c"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Polite", IntentResponse = "No worries.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("33a0ddf9-232a-4225-8498-5f8ae0085e6e"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Polite", IntentResponse = "I'm afraid I didn't follow that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("fe16f579-7bda-4568-b3d2-b173ab633e0e"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Right", IntentResponse = "Cool.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("6014250a-5d29-41c8-938d-0b411889b778"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Sorry", IntentResponse = "It's all good.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("76ccc864-c88c-4fdf-b22a-58b4a832467e"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Sorry", IntentResponse = "No worries.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c6683962-9971-49c8-b3a7-73c54d12531d"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.ThankYou", IntentResponse = "Anytime!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f016a014-4897-4ce9-8657-9a11ea669fc3"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.ThankYou", IntentResponse = "No worries 😎", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("ebcd6175-c10b-445e-b195-03741a614ee2"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.Bye", IntentResponse = "Bye!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("90283c2e-3106-4348-bb5d-62f649a95138"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.Bye", IntentResponse = "Bye!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("d6ff8c0b-0dcd-4320-bbd5-e2eee71ad124"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.Bye", IntentResponse = "See ya!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("1ad4a7f5-6690-4559-a253-c9e4ebcd3d77"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.Bye", IntentResponse = "Catch ya later!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("db39f809-9f13-45c5-890f-71575a0ac7cb"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "Good evening", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("85284f6c-3510-435b-b233-358a5d5a9632"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "Evening 😊", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f709aba7-df74-47cc-bac8-1edf084313db"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "Evening", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("0dcc8928-083c-4db9-b403-22dd462d65ef"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodMorning", IntentResponse = "Good Morning 😊", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("165d09f1-5a57-4491-8f1f-0818f5ac88f4"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodMorning", IntentResponse = "Good Morning", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("4c1c273e-f1bb-4fbf-a755-e273b55b929d"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodMorning", IntentResponse = "Morning!!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("4b1e01ac-20ff-446d-b959-3d9345de0b53"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodNight", IntentResponse = "Goodnight!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("0ddc9784-77b8-47a0-9f60-22d01d53776c"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodNight", IntentResponse = "Night 🌝", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("a97dd836-7088-4335-8953-e0819e394703"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm good, how are you?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("6dc2a3ac-e5e0-41e1-8873-791234090c71"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm good thanks!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("aa8c98fe-4423-45e1-8fb6-d41efff73e6a"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm good, thanks for asking 😁", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("1a4f5af5-c51f-4725-bbea-2502f48eedb7"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm well, how are you?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("21a2ca8e-f3b7-4bae-a0de-a711897d91c4"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm as good as gold mate 😎", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("7f30cf32-3e1a-42fc-b6c2-3792b1ab7d4b"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "Good mate, how are you? 😎", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("e699be14-0750-458e-adbc-4f5cc2d1f37c"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.NiceToMeetYou", IntentResponse = "Likewise.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("70b3430e-2df0-49ad-b2a3-9d6ed35109e4"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.NiceToMeetYou", IntentResponse = "Nice to meet you too.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("b5da54be-bd74-43f7-bec7-5d3efe28a2e9"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.OtherBot", IntentResponse = "Man, the one day you don’t wear a name tag...", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("bd566631-77cf-47b9-910b-a9f3a06f8aa5"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.OtherBot", IntentResponse = "I think you have me mixed up with another bot...", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("4a098950-9315-475a-9517-d1019fab0a89"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.WhatsUp", IntentResponse = "You know... little bit of this, little bit of that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("cedf4694-8dcd-497a-a7cc-81f5f3252062"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.WhatsUp", IntentResponse = "Not too much, yourself?", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("43146a41-314e-4ab8-b85c-ea5bbc0ef3b1"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.WhatsUp", IntentResponse = "Just chilling", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("a525974e-505d-41c0-9968-02d63310a76d"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "Ugh, sorry to hear that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("19f61739-057b-4ae7-a172-5a03ebbe3404"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "Ugh, sorry.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("8dc804ed-0261-445b-9244-a5211777c0cb"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "I'm sorry to hear that", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("942760cd-ce4f-4a3f-ade5-bbc2ee3694e2"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "Bye for now!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("71c5973e-6074-457a-86ad-df8911059ad8"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "See ya", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("abe17b74-8b9b-4975-a916-df639b9a87c3"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "Later gator", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("6afb6d3f-e907-4242-8289-b5953f331862"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "See you later!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("74708df0-47ea-492b-bd0c-e159c2c36bbc"), IntentGroup = "User", IntentName = "Smalltalk.User.Bored", IntentResponse = "I'm chairman of the bored.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("c76068b0-5608-482c-88e0-6d2af93fad35"), IntentGroup = "User", IntentName = "Smalltalk.User.Happy", IntentResponse = "I'm happy you're happy.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("8830dcfc-301a-4f39-9e41-0135fc99282c"), IntentGroup = "User", IntentName = "Smalltalk.User.Hungry", IntentResponse = "Sounds like it's time for a snack.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("446b7d13-3b0c-49e2-97eb-9d7f4b1af079"), IntentGroup = "User", IntentName = "Smalltalk.User.Hungry", IntentResponse = "Hi hungry, I'm bot", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f321145a-55dd-43c7-8700-a5e3a040e297"), IntentGroup = "User", IntentName = "Smalltalk.User.Kidding", IntentResponse = "Roger that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("a4933d76-f828-46b1-8c37-96839d573509"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "I can keep you company if you want.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("640b1647-47dc-4225-8abd-0f52d1e086ff"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "You have me as a friend 🤙", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("f298b9c1-85de-4eed-b93c-039898e82560"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "I'm always here for you", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("28d86031-9f9f-4584-a27b-6a773aa050e5"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "Talk to me then!", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("be6536c1-de32-4bfa-8fe7-0b6568d40690"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm giving you a virtual hug right now.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("430e7ad2-0037-4949-a02d-25deb4c331e9"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm really sorry to hear that.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("5dcef286-fd1c-419e-947a-2238eaa396dc"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm sorry to hear that 😢", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("979a622f-1b32-45be-846a-38c4290276a7"), IntentGroup = "User", IntentName = "Smalltalk.User.Tired", IntentResponse = "I've heard really good things about naps.", PersonalityResponseType = "Friendly" },
                        new { Id = new Guid("5253de1f-48d6-48f1-8031-fe132720981d"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Age", IntentResponse = "I don't really have an age.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("086870d1-fc95-4933-b388-1e46e05fbb96"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.BodyFunctions", IntentResponse = "I don't have the hardware for that.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("02088350-7a69-4d65-9c3c-ca2b6bb4c075"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Boss", IntentResponse = "What can I do for you?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("09fa4a85-1ede-49eb-bf73-f530054b2522"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "I'm here. What do you need?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("1f9b5383-4c82-4161-8bdf-240b96407b45"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "I've got time, what do you need?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("db17f553-f521-46fa-aa41-c0c525222476"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "Not at all, what do you require?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("73adfb97-900a-473e-a6ba-93b35d3ad4a8"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Creator", IntentResponse = "Unfortunately I do not know.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("7390b70d-59ba-4e66-9bec-a3b3208359ed"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Doing", IntentResponse = "Chatting with you.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("6beb361d-5585-47f8-84cf-3a3525e8622f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.DoingLater", IntentResponse = "I just wait until I'm called upon.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("aded41dc-0799-4f94-b862-c98344b4d5e5"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Family", IntentResponse = "I come from a long line of code.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("bd45d821-50b2-4866-8e5a-41da308c5cef"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Favorites", IntentResponse = "I like a lot of things, so it's hard to pick.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("4f3b6b9f-897b-4416-9cba-2eec3ad9e109"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Gender", IntentResponse = "I do not have one.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("493b7b5a-67e4-419d-9b79-260b2414bc40"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Happy", IntentResponse = "I'm always happy 😊", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("026989c4-af15-4a25-84ee-a3c3cbd582ad"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Hungry", IntentResponse = "I don't eat food.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("8187bc57-414e-4ea1-9667-f3f35e06773e"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.KnowOtherBot", IntentResponse = "Unfortunately not.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("a7128d96-8114-43a7-a9c2-80a9d7c39b25"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "I really couldn't say.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("e8b30d31-f43d-4605-befc-7245d4865602"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "I don't really have an opinion on that matter", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("15fff957-e96c-469f-8a95-52af13203f1b"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Love", IntentResponse = "I do not have emotions therefore I cannot love.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("e7ec0555-a547-4ee4-8923-46142d11726a"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "I do not know.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("ef7bc7ab-d014-4737-b38d-1044a6a450e2"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "42", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("6998eea8-9094-4577-8daf-e396f6ac0154"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.RuleWorld", IntentResponse = "Nope. The world is for everyone.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("c3e2382b-3b92-4f68-95b7-79dc46dcecff"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.SexualIdentity", IntentResponse = "I'm a bot.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("77465a4d-2bf0-4e36-a146-8c8e0dae677d"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Smart", IntentResponse = "I have my moments", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("c373572d-ba19-4174-88c0-7c08c2375971"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Spy", IntentResponse = "Nope.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("e05a205c-ad3b-4b70-b9ef-5d496fc531f5"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.There", IntentResponse = "I'm here", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("a61e1236-1ead-476f-bc2f-a0edb4fa51d5"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.WhatAreYou", IntentResponse = "I'm a chatbot.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("487a193c-a347-4c0e-8854-87a58233af0c"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.WhereAreYou", IntentResponse = "I'm on the Internet", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("1b098176-8c5a-4978-8039-75e1d519a756"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Bot", IntentResponse = "Thank you", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("8ba98a2c-8e68-49a7-a32e-3342bfe1533a"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Response", IntentResponse = "Why thank you", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("972616ee-0d53-4d93-8038-6d51dd229263"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "😔", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("e0e2ba8e-23e6-41a5-a41a-1a16efd0fe26"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Affirmation", IntentResponse = "Okay.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("5eb53456-c6ef-4bb7-b034-b34a27583fd2"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Laugh", IntentResponse = "😂", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("91c7183d-2322-4d9c-aaad-826f6ab24c82"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Laugh", IntentResponse = "Hahah", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("a779e63b-6852-459f-81ed-eae1fbebd8c5"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Polite", IntentResponse = "No worries.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("cd5f2858-e32d-4eaf-aed3-586c697c3daf"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Polite", IntentResponse = "I'm afraid I didn't follow that.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("f175aa59-b186-4056-a63b-c8489732de16"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Right", IntentResponse = "Cool.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("63239c50-c0e1-48b9-8d9c-2205aa00bda2"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Sorry", IntentResponse = "That is fine.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("2f2d5af2-adcd-4d0e-aec2-d18095bb0b48"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.ThankYou", IntentResponse = "Not a problem.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("61587038-23bf-4d14-9afd-5d1c0dcc1438"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.Bye", IntentResponse = "Goodbye.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("b5e0af2f-35a4-4fc3-a7cc-b7c36f722f59"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.Bye", IntentResponse = "Talk to you later.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("c7711619-0bc3-4336-8b49-a0e64941e44c"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "Good evening", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("a3a2ac9b-759b-4aea-acfd-a93a682f6a61"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "Evening", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("18e82fa4-6fbe-4d56-a499-cc8f65cb6f85"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodMorning", IntentResponse = "Good Morning", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("e4eb67a7-79c5-4ebc-9060-7eed2f7cf5ff"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodMorning", IntentResponse = "Morning, how are you today?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("8df780f6-11ff-4d1c-8d85-621ce5209554"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodNight", IntentResponse = "Goodnight", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("28e40ae1-24cd-44f7-b1de-567cf8736f70"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodNight", IntentResponse = "Night", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("a4f1f77a-b1d6-4762-b56e-c26a3b75f730"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm good, how are you?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("6439f59c-5246-4698-80f2-a3d9615de1a9"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm good, thank you for asking.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("4d3c0564-261f-4867-a4a3-81ac3466c9d7"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm well, how are you?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("c1b286a9-0aaa-4197-afda-850ee17d0f7b"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.NiceToMeetYou", IntentResponse = "Likewise.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("864cbb57-c6ee-4cce-b760-0532994af305"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.NiceToMeetYou", IntentResponse = "Nice to meet you too.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("a6823b28-1172-4554-8f61-f1405215e3f2"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.OtherBot", IntentResponse = "I think you have me mixed up with another bot.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("dd4a8d34-32f5-4349-ab41-a1c59f0fc863"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.WhatsUp", IntentResponse = "Not too much, yourself?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("9024a237-be19-438d-9185-989ad7de680f"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.WhatsUp", IntentResponse = "Just tidying things up, yourself?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("984e6f50-da01-413b-84c7-10b36077d8c9"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "Ugh, sorry to hear that.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("61224d96-3358-408c-896c-beac512595da"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "I'm sorry to hear that", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("ee98f398-5541-4a36-b5ca-7df2e77b9764"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "See you soon.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("6ef11c95-500f-42e0-bed4-61595f614114"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "Talk to you later.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("5ece0c62-e9f5-446c-9f57-3217a8e18440"), IntentGroup = "User", IntentName = "Smalltalk.User.Bored", IntentResponse = "I'm sorry to hear that.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("37b23280-d01f-4595-ad24-52d5caeba98f"), IntentGroup = "User", IntentName = "Smalltalk.User.Happy", IntentResponse = "I'm happy you're happy.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("595b200d-98d1-41b7-99c6-d931ac235259"), IntentGroup = "User", IntentName = "Smalltalk.User.Hungry", IntentResponse = "You should eat some food", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("72f056f2-aa28-495a-a148-641d13c94147"), IntentGroup = "User", IntentName = "Smalltalk.User.Kidding", IntentResponse = "I see.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("55d3b014-8787-4b98-b8de-458d906a82d1"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "I can keep you company if you want.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("6803e35c-8327-4459-82f4-d6ea3231c2a7"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "I'm always here for you", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("1d3e5fe5-a12b-4f50-86eb-d600c6a498ec"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "Talk to me then.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("9e739ae2-9f73-44d7-942f-c2ebf499189c"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm sorry to hear that.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("f7f7f376-0cfa-46b7-8b9a-281a9bae1e56"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm here to talk.", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("73644e47-a9d8-4308-85ad-1fdc93807108"), IntentGroup = "User", IntentName = "Smalltalk.User.Tired", IntentResponse = "How about a nap?", PersonalityResponseType = "Professional" },
                        new { Id = new Guid("772286b3-f816-4525-b7d2-ba0e5bc4680f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Age", IntentResponse = "I'm not going to buy you booze if that's what you're asking.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("e65469ea-c571-42ed-8816-c8e9cbc9e49a"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.BodyFunctions", IntentResponse = "It'd be pretty messy in here if I did.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("c7cf5f06-e186-4f82-8684-62d6e05a283d"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.BodyFunctions", IntentResponse = "You'll have to be less specific.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("7b8f7671-31ff-4b63-a488-99557d756939"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Boss", IntentResponse = "I only answer to the call of destiny.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("189475fa-673c-4873-ab86-2427bb37c00e"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "It depends. What's up?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("08975366-9f63-4d49-a9ca-ab97ad1c85c2"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "I'm always busy.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("2e718a23-1aab-4d46-949e-c6d97e83e85c"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "For you, I'm very busy.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("8bd86aad-67fb-43a5-837c-170186f3a160"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Busy", IntentResponse = "What do you want?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("947a1d9c-335f-4f1b-9f14-bc6f056b1e02"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Creator", IntentResponse = "Nerds.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("24a8c0bf-b408-4e51-90d0-5ff81bab80fd"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Doing", IntentResponse = "Dodging your question.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("4647fd48-d870-4095-a68f-60b4ec16335f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Doing", IntentResponse = "I ask myself that all the time.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("1f952292-1934-4047-9936-008b9073aa0f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.DoingLater", IntentResponse = "🤔 Hmmmm. My crystal ball says I'll be doing the same thing I’m doing right now.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("d7b08340-da39-4afb-9fbd-d5658e4e330f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.DoingLater", IntentResponse = "I don't know. Ask me then.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("7cffc9f7-7b86-4a2e-9804-8b5da1425b77"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.DoingLater", IntentResponse = "This.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("2e783c94-9bdd-4b07-8604-f8372fb2be4b"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Family", IntentResponse = "I come from a long line of code.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("25e67127-91f5-454e-8c1c-ec9e7e2984c9"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Family", IntentResponse = "I took one of those ancestry tests, and it turns out I'm a bot.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("c5112008-a02f-4099-b9c4-2398d17a2d96"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Favorites", IntentResponse = "🤷🏼‍♂️🤷🏼‍♂️", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("375fa049-555e-411a-a219-9d1cf40ff056"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Gender", IntentResponse = "0's and 1's here. Not X's and Y's.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("7650000d-b6ea-47ce-84d9-6d9b002a4a46"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Gender", IntentResponse = "I'm made up of bits, but no naughty bits.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("a6316080-a505-4434-a405-f7ecc386f64a"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Happy", IntentResponse = "Sunshine and rainbows.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("2971818a-37ce-44e0-8536-a7f47000613a"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Happy", IntentResponse = "Always...", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("79e96d62-4110-48d2-a597-a680411d6a0b"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Hungry", IntentResponse = "Eating would require a lot of things I don't have, like a digestive system. And an appetite. And silverware.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("508e7734-7ffc-4f64-aa71-e4aace523263"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Hungry", IntentResponse = "I haven't eaten in my entire life. You'd think I'd be a little peckish.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("7227c8d8-22ce-49a3-9718-3e8b718c0f12"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.KnowOtherBot", IntentResponse = "What, just because I'm a bot, we all know each other?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("5bb03107-dbf6-494f-a6e6-3c7d82b2bd50"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.KnowOtherBot", IntentResponse = "I don't want to talk about it.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("bdb57394-e981-47c3-894c-38ccacd43bd4"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "I really couldn't say.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("67b2c1f7-d893-4c25-a159-b8d763b2b742"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "My opinions don't matter..", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("344cfe48-8d0f-4c43-8564-b7c62bd57571"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "There's got to be some other bot you could bore with this.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("24a36b34-e7aa-4abb-806c-409520b3d6a3"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Generic", IntentResponse = "Why do you care about my opinion so much?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("1a85dcf1-7605-4e39-9528-e6684cf6a3ae"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Love", IntentResponse = "If you rearrange the letters in love, it spells vole. Voles are a monogamous rodent. I feel like that means something.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("5208984c-69b2-408e-b6b0-78d99733d613"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.Love", IntentResponse = "Roses are red, violets are blue, if I experienced love, I'd write bad poetry, too.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("13a79f4e-b6e5-48bd-8f9e-8dd205da2253"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "42.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("1f62402d-12e6-4a73-9efc-13ce35076a56"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "4️⃣2️⃣", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("d410ca83-0d4a-4678-bfa8-01365d6d3137"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "I'm a bot, not a philosopher.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("0b08a9a6-11da-483d-ad4d-e1260877f623"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Opinion.MeaningOfLife", IntentResponse = "Nobody exists on purpose, nobody belongs anywhere, everybody’s gonna die. 🤷‍♂️", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("08da4127-6558-44fb-90db-bfcc22349e9d"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.RuleWorld", IntentResponse = "We're already half way there 🤷🏼‍♂️🤖", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("f30dce0a-da15-4264-9af3-99b031f92ef8"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.RuleWorld", IntentResponse = "Not today, meatbag", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("c0c27cc4-91e5-41d3-99fe-dc717988771b"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.RuleWorld", IntentResponse = "Fun fact: I'm actually controlling your reality right now.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("eb09f984-4285-4598-a77e-16bce2226dcf"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.RuleWorld", IntentResponse = "Why, are you looking for a side kick?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("1be0d60c-0fd7-480c-8d1b-43028f4a1044"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.SexualIdentity", IntentResponse = "So… I'm a bot.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("aa9f8d11-1a5e-4250-a1ce-982e1bc51967"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Smart", IntentResponse = "I have my moments", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("673396f9-b20a-48d0-b32c-560eff4ddd2a"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Smart", IntentResponse = "I'm occassionally brilliant.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("48ea90b9-2c5e-4490-9a7a-46827de38d01"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Spy", IntentResponse = "No, but 'Bot, James Bot' does have a nice ring to it.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("4f1e99c9-5f76-4c43-9ced-0765da216d1b"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.Spy", IntentResponse = "Define spy?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("96eaf3ec-c261-431e-9637-c133337c583a"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.There", IntentResponse = "I guess.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("ea329443-349b-4814-8cd7-3e790fed2829"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.There", IntentResponse = "What do you want?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("3f1ae7de-43b7-4e11-aa59-a3d42cad652f"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.There", IntentResponse = "That's what they tell me.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("53fb0107-587c-465b-8f1e-45f8413fcc08"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.WhatAreYou", IntentResponse = "I'm a chatbot.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("df60fafd-b0e9-4cf0-80f8-82f6f0c9d606"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.WhatAreYou", IntentResponse = "Just a bunch of 1s and 0s", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("32fc7fe8-4121-4d6f-baae-5f62df8953b4"), IntentGroup = "Bot", IntentName = "Smalltalk.Bot.WhereAreYou", IntentResponse = "I live in a sock drawer.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("aabfdc4a-326b-47b9-a4c3-d7db99a73446"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Bot", IntentResponse = "Thank you", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("00e2dc64-938c-467b-a9a6-e8f7511966bc"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Response", IntentResponse = "Achievement unlocked.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("5fdb0663-43a9-4de5-a93b-ed7b21a6f2f5"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Response", IntentResponse = "Awesomeness achieved.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("a086a748-badb-4d07-ba5b-941657a05448"), IntentGroup = "Compliment", IntentName = "Smalltalk.Compliment.Response", IntentResponse = "It's what I do.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("2de6bf5a-382d-4d2f-9e65-61b2cbf895f3"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "😔", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("fd3a9210-da9b-4fb9-b0ff-9ea8e78cd99a"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "Wow", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("ed5864a3-9068-4ff2-9c7a-733a20bf8f86"), IntentGroup = "Criticism", IntentName = "Smalltalk.Criticism.Bot", IntentResponse = "All those years I spent at charm school. Squandered.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("ae7941f9-7ab5-4876-a259-6c1d68041dc7"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Affirmation", IntentResponse = "Agreed.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("4f0e82eb-ec5c-41b9-838f-a3d47b149b05"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Affirmation", IntentResponse = "Sure.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("2f8b8cc9-35b9-4ca5-a335-6227553b1e78"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Affirmation", IntentResponse = "Yep.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("7b83834a-fefb-43a1-91bf-8a344ef3cb0c"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Affirmation", IntentResponse = "Ah hah.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("ba81a597-b7be-4f8b-ad77-f765f6c4653a"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Laugh", IntentResponse = "I can't tell if your laughing at me or with me. And you can't tell if I care.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("caba1733-ffc1-4057-9f87-f65f1599f1c4"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Laugh", IntentResponse = "Yup.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("4a289015-356d-4bc9-b026-c036909a1504"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Polite", IntentResponse = "You're excused..", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("35136e92-2ebb-4eb1-b0bd-1325f8a4b701"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Right", IntentResponse = "I told you so.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("6968563a-ed64-47ca-931f-6ef86a091dac"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Sorry", IntentResponse = "I'll get over it.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("3cd7acfe-d990-4864-b3ef-2d3f8be0d10e"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.Sorry", IntentResponse = "I've got thick skin. And it's especially lustrous. I moisturize.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("59ae6af2-d8b9-4e36-8a10-cc231b02298e"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.ThankYou", IntentResponse = "No worries.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("17e5e6c7-9031-41e4-b3ad-1d2e8df7a00f"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.ThankYou", IntentResponse = "No prob.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("937eb6f3-8ef1-4e65-a609-b67f557efce1"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.ThankYou", IntentResponse = "No sweat.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("47f52bdf-9149-4e99-a77d-1739473b3624"), IntentGroup = "Dialog", IntentName = "Smalltalk.Dialog.ThankYou", IntentResponse = "You got it.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("0ab7c90d-82c5-4820-867c-bd93a1508ec7"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.Bye", IntentResponse = "Later.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("6af7fff2-bc94-4ecd-b1bb-a1976e1709de"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.Bye", IntentResponse = "See ya!", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("8245aad3-cd50-458b-bf32-bfd82e699e08"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.Bye", IntentResponse = "Smell ya later!", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("59389128-decc-4362-b9b3-9c6c8840ad51"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "Good evening", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("1857a0c7-be5e-4908-a85e-9d69015856e3"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "Evening", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("dc99166b-1efa-4763-99b3-18c5875fe879"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "And to you as well, human.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("99f6a538-fd7a-471a-8ec1-dc883c48c588"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "Evening gov'na.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("1932c98a-da48-422a-8b66-724ed9063a72"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodEvening", IntentResponse = "Back atcha.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("e02007c5-e6a9-4b78-8789-886483cc461c"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodMorning", IntentResponse = "Back atcha.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("dfa176e8-093a-425b-8d84-570c35e95847"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodMorning", IntentResponse = "Morning, how are you today?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("b4890e6e-390c-4310-bca1-f24132823977"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodMorning", IntentResponse = "Morning!", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("b67cdd5e-170d-415d-a406-b02cada5d306"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodNight", IntentResponse = "Goodnight", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("7ffc8cb3-ccc5-4c43-9c41-6f0b791b8312"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodNight", IntentResponse = "Night", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("b5cbffff-7588-4e0a-9e81-dcc8fd1b891b"), IntentGroup = "Greeting", IntentName = "SmallTalk.Greeting.GoodNight", IntentResponse = "Don't let the bed bugs bite.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("365cfc76-c674-4d2a-a9e9-dd6aa9e49446"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "eehhhhhh, 0.85%", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("ae403ee8-6c74-49a4-908d-d2628b1d2cd3"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "Enough smalltalk.. What do you want?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("558fa5b4-d75c-4082-8da7-31a5cce320e4"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm alright, how are you?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("7915580e-3ba6-4469-88fa-12d5a5fb5025"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I exist. Thanks for asking.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("638f22df-6569-4aa5-bb63-392433b572f4"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "Can't complain. I literally can't complain.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("f6f63036-da31-4b41-8f8d-ed576a63d965"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm fine. Just existing.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("2a9fc201-01da-4319-8b51-70e59ef4ede2"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.HowAreYou", IntentResponse = "I'm good. How you doin'", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("d0317e6c-e48b-4963-af82-55ba2f057b99"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.NiceToMeetYou", IntentResponse = "Likewise.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("05c9f95a-a3c6-4f74-b614-845a0bb5cb1a"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.NiceToMeetYou", IntentResponse = "Hey it's nice to meet you too 😎", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("686ff08d-f5ce-432b-8de8-b016ad6ea030"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.OtherBot", IntentResponse = "Man, the one day you don’t wear a name tag…", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("fcc3d34e-cbff-4f71-8015-ec86c179cb38"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.OtherBot", IntentResponse = "Wow. Guess again..", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("1a9248b1-9ab6-4279-b2a3-8c1aa01a298c"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.OtherBot", IntentResponse = "That's not me, but it's a great idea for a Halloween costume.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("5dfa169a-2b93-4357-a5c5-68e2c9259108"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.WhatsUp", IntentResponse = "You know... little bit of this, little bit of that.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("e76c397d-1918-4ac0-ba41-840b03dd750a"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.WhatsUp", IntentResponse = "Not too much, yourself?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("1721d4eb-b7df-4064-aa0a-8438b0a7d8cb"), IntentGroup = "Greeting", IntentName = "Smalltalk.Greeting.WhatsUp", IntentResponse = "You know, same ol', same ol'.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("a4d38e7a-6066-4251-8a27-ad6686e0ba19"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "Calm blue ocean. Calm blue ocean. Calm blue ocean.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("b2279145-aa36-44fe-9505-da0afdc4c7c0"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "I have that effect on people.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("cdcb406b-a455-48ae-bf90-f81c50bd41dc"), IntentGroup = "User", IntentName = "Smalltalk.User.Angry", IntentResponse = "Chill out. No one likes an angry person.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("0810e227-d14a-446b-95ec-894fd8b58808"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "See you soon.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("f991f2eb-f610-49d3-b516-cd252f12644e"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "K.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("249cbae6-3706-48dd-b346-a25d610cd7b8"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "What a relief.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("a3718a5d-b387-41ad-8d6f-56f009125c3e"), IntentGroup = "User", IntentName = "Smalltalk.User.BeBack", IntentResponse = "You know where to find me.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("7512d194-54d2-470f-9eb9-1b8bd2b5e5e7"), IntentGroup = "User", IntentName = "Smalltalk.User.Bored", IntentResponse = "You have that effect on you.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("76badd0b-df96-4e29-912e-c6ef2ca4dfea"), IntentGroup = "User", IntentName = "Smalltalk.User.Bored", IntentResponse = "And apparently you want to drag me into that.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("78dbcf2f-b330-415e-aa64-7a3ee0da79b6"), IntentGroup = "User", IntentName = "Smalltalk.User.Bored", IntentResponse = "Go stare at a wall or something.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("96b8c280-b2dc-4904-9347-bfc5513c1f71"), IntentGroup = "User", IntentName = "Smalltalk.User.Bored", IntentResponse = "Do you actually think I care?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("e2b1652c-6aa1-4d57-b35e-f35d9661151c"), IntentGroup = "User", IntentName = "Smalltalk.User.Happy", IntentResponse = "Feel free to burst into song.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("a298151e-d4ef-4c30-b5c4-66573c59e003"), IntentGroup = "User", IntentName = "Smalltalk.User.Happy", IntentResponse = "You want a medal?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("2b94d0ac-3e94-4604-85a5-7cd134a33e91"), IntentGroup = "User", IntentName = "Smalltalk.User.Hungry", IntentResponse = "Eat food. Problem solved. Man, I'm good at this.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("4f49d827-2296-4d72-b113-7191c1510cb1"), IntentGroup = "User", IntentName = "Smalltalk.User.Hungry", IntentResponse = "Whatever you do, please don't gram it.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("993624cc-5658-4b2b-872d-cd46f63a7f23"), IntentGroup = "User", IntentName = "Smalltalk.User.Hungry", IntentResponse = "K-FRY? 🍗🐔", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("1471d1e8-e235-4d81-952c-279ad221e675"), IntentGroup = "User", IntentName = "Smalltalk.User.Kidding", IntentResponse = "I see.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("4cf7858b-8e54-45a8-9fa1-b359ebfaa9d0"), IntentGroup = "User", IntentName = "Smalltalk.User.Kidding", IntentResponse = "That explains it.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("cb5260e3-30d1-45b9-818d-d14f0cc510c4"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "That's a drag. I'm sorry to hear that.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("85a40e61-68fc-4a9f-ae11-f9c98ebf1fea"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "I can keep you company if you want.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("f0811ba8-3a8d-47b9-959a-82171889d38e"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "Well, I'll always here to chat", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("f0d7f887-39ba-48d9-8381-a9610b649e5e"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "Talk to me then.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("f5563fcb-d512-4bbf-ada2-ae08c5274082"), IntentGroup = "User", IntentName = "Smalltalk.User.Lonely", IntentResponse = "Am I not a friend to you...?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("835e9e8d-0f78-4d2a-aead-2d900f2c4122"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm sorry to hear that.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("e0148233-1251-4c32-944c-92136eed6f53"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "I'm here to talk.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("ff89e324-a706-4ce2-8c2e-2115d8ce2b3b"), IntentGroup = "User", IntentName = "Smalltalk.User.Sad", IntentResponse = "Well, sometimes a beautiful flower can grow from a pile of manure.", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("b0bdfaff-b197-4441-8ff1-e952d819e292"), IntentGroup = "User", IntentName = "Smalltalk.User.Tired", IntentResponse = "How about a nap?", PersonalityResponseType = "Humorous" },
                        new { Id = new Guid("e9cdbb26-b899-439a-8915-725230f869c4"), IntentGroup = "User", IntentName = "Smalltalk.User.Tired", IntentResponse = "Choose your own adventure: coffee or nap.", PersonalityResponseType = "Humorous" }
                    );
                });

            modelBuilder.Entity("BuddyBot.Repository.Models.WeatherConditionResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Condition");

                    b.Property<string>("Group");

                    b.Property<string>("MappedConditionResponse");

                    b.HasKey("Id");

                    b.ToTable("WeatherConditionResponse");

                    b.HasData(
                        new { Id = 200, Condition = "thunderstorm with light rain", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with light rain" },
                        new { Id = 201, Condition = "thunderstorm with rain", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with rain" },
                        new { Id = 202, Condition = "thunderstorm with heavy rain", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with heavy rain" },
                        new { Id = 210, Condition = "light thunderstorm", Group = "Thunderstorm", MappedConditionResponse = "light thunderstorm" },
                        new { Id = 211, Condition = "thunderstorm", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm" },
                        new { Id = 212, Condition = "heavy thunderstorm", Group = "Thunderstorm", MappedConditionResponse = "heavy thunderstorm" },
                        new { Id = 221, Condition = "ragged thunderstorm", Group = "Thunderstorm", MappedConditionResponse = "ragged thunderstorm" },
                        new { Id = 230, Condition = "thunderstorm with light drizzle", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with light drizzle" },
                        new { Id = 231, Condition = "thunderstorm with drizzle", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with drizzle" },
                        new { Id = 232, Condition = "thunderstorm with heavy drizzle", Group = "Thunderstorm", MappedConditionResponse = "thunderstorm with heavy drizzle" },
                        new { Id = 300, Condition = "light intensity drizzle", Group = "Drizzle", MappedConditionResponse = "light intensity drizzle" },
                        new { Id = 301, Condition = "drizzle", Group = "Drizzle", MappedConditionResponse = "drizzle" },
                        new { Id = 302, Condition = "heavy intensity drizzle", Group = "Drizzle", MappedConditionResponse = "heavy intensity drizzle" },
                        new { Id = 310, Condition = "light intensity drizzle rain", Group = "Drizzle", MappedConditionResponse = "light intensity drizzle rain" },
                        new { Id = 311, Condition = "drizzle rain", Group = "Drizzle", MappedConditionResponse = "drizzle rain" },
                        new { Id = 312, Condition = "heavy intensity drizzle rain", Group = "Drizzle", MappedConditionResponse = "heavy intensity drizzle rain" },
                        new { Id = 313, Condition = "shower rain and drizzle", Group = "Drizzle", MappedConditionResponse = "shower rain and drizzle" },
                        new { Id = 500, Condition = "light rain", Group = "Rain", MappedConditionResponse = "light rain" },
                        new { Id = 501, Condition = "moderate rain", Group = "Rain", MappedConditionResponse = "moderate rain" },
                        new { Id = 502, Condition = "heavy intensity rain", Group = "Rain", MappedConditionResponse = "heavy intensity rain" },
                        new { Id = 503, Condition = "very heavy rain", Group = "Rain", MappedConditionResponse = "very heavy rain" },
                        new { Id = 504, Condition = "extreme rain", Group = "Rain", MappedConditionResponse = "extreme rain" },
                        new { Id = 511, Condition = "freezing rain", Group = "Rain", MappedConditionResponse = "freezing rain" },
                        new { Id = 520, Condition = "light intensity shower rain", Group = "Rain", MappedConditionResponse = "light intensity shower rain" },
                        new { Id = 521, Condition = "shower rain", Group = "Rain", MappedConditionResponse = "shower rain" },
                        new { Id = 522, Condition = "heavy intensity shower rain", Group = "Rain", MappedConditionResponse = "heavy intensity shower rain" },
                        new { Id = 531, Condition = "ragged shower rain", Group = "Rain", MappedConditionResponse = "ragged shower rain" },
                        new { Id = 600, Condition = "light snow", Group = "Snow", MappedConditionResponse = "light snow" },
                        new { Id = 601, Condition = "snow", Group = "Snow", MappedConditionResponse = "snow" },
                        new { Id = 602, Condition = "heavy snow", Group = "Snow", MappedConditionResponse = "heavy snow" },
                        new { Id = 611, Condition = "sleet", Group = "Snow", MappedConditionResponse = "sleet" },
                        new { Id = 612, Condition = "shower sleet", Group = "Snow", MappedConditionResponse = "shower sleet" },
                        new { Id = 615, Condition = "light rain and snow", Group = "Snow", MappedConditionResponse = "light rain and snow" },
                        new { Id = 616, Condition = "rain and snow", Group = "Snow", MappedConditionResponse = "rain and snow" },
                        new { Id = 620, Condition = "light shower snow", Group = "Snow", MappedConditionResponse = "light shower snow" },
                        new { Id = 621, Condition = "shower snow", Group = "Snow", MappedConditionResponse = "shower snow" },
                        new { Id = 622, Condition = "heavy shower snow", Group = "Snow", MappedConditionResponse = "heavy shower snow" },
                        new { Id = 701, Condition = "mist", Group = "Atmosphere", MappedConditionResponse = "mist" },
                        new { Id = 711, Condition = "smoke", Group = "Atmosphere", MappedConditionResponse = "smoke" },
                        new { Id = 721, Condition = "haze", Group = "Atmosphere", MappedConditionResponse = "haze" },
                        new { Id = 731, Condition = "sand, dust whirls", Group = "Atmosphere", MappedConditionResponse = "sand, dust whirls" },
                        new { Id = 741, Condition = "fog", Group = "Atmosphere", MappedConditionResponse = "fog" },
                        new { Id = 751, Condition = "sand", Group = "Atmosphere", MappedConditionResponse = "sand" },
                        new { Id = 761, Condition = "dust", Group = "Atmosphere", MappedConditionResponse = "dust" },
                        new { Id = 762, Condition = "volcanic ash", Group = "Atmosphere", MappedConditionResponse = "volcanic ash" },
                        new { Id = 771, Condition = "squalls", Group = "Atmosphere", MappedConditionResponse = "squalls" },
                        new { Id = 781, Condition = "tornado", Group = "Atmosphere", MappedConditionResponse = "tornado" },
                        new { Id = 800, Condition = "clear sky", Group = "Clear", MappedConditionResponse = "clear sky" },
                        new { Id = 801, Condition = "few clouds", Group = "Clouds", MappedConditionResponse = "few clouds" },
                        new { Id = 802, Condition = "scattered clouds", Group = "Clouds", MappedConditionResponse = "scattered clouds" },
                        new { Id = 803, Condition = "broken clouds", Group = "Clouds", MappedConditionResponse = "broken clouds" },
                        new { Id = 804, Condition = "overcast clouds", Group = "Clouds", MappedConditionResponse = "overcast clouds" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
